### ISSUE TITLE
Project import fails with UnboundLocalError

### ISSUE THREAD

**Issue by jloeser** [aplanas/obsgit#13]
Importing an just exported project (within same OBS instance) fails with:

```
$ ./obsgit -l DEBUG import ./prj-export test:prj
DEBUG:asyncio:Using selector: EpollSelector
Git LFS extension enabled in the repository
DEBUG:__main__:Start upload to source/test:prj/_attribute
DEBUG:__main__:Start upload to source/test:prj/_meta
DEBUG:__main__:Start upload to source/test:prj/_pattern
Traceback (most recent call last):
  File "./obsgit", line 1212, in <module>
    loop.run_until_complete(args.func(args, config))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "./obsgit", line 1109, in import_
    await importer.project(project)
  File "./obsgit", line 762, in project
    await self.project_metadata(project)
  File "./obsgit", line 807, in project_metadata
    for meta in metadata
  File "./obsgit", line 129, in upload
    await self._upload(url_path, filename_path=filename_path, data=data, **params)
  File "./obsgit", line 123, in _upload
    if resp.status != 200:
UnboundLocalError: local variable 'resp' referenced before assignment
```

It makes not difference if the target project already exists or not. Using `--skip-project-meta`does also not help, neither trying only one package.

```
$ git show-ref --abbrev HEAD
ac6e396 refs/remotes/upstream/HEAD
$ python --version
Python 3.6.10
$ pip list
Package           Version
----------------- -------
aiohttp           3.6.2
async-timeout     3.0.1
asyncio           3.4.3
attrs             19.3.0
cached-property   1.5.1
cffi              1.14.0
chardet           3.0.4
idna              2.9
idna-ssl          1.1.0
multidict         4.7.6
pip               20.1.1
pycparser         2.20
pygit2            1.2.1
setuptools        47.3.1
typing-extensions 3.7.4.2
wheel             0.34.2
yarl              1.4.2
$ osc -A ... api /about
<about>
  <title>Open Build Service API</title>
  <description>API to the Open Build Service</description>
  <revision>2.10.5</revision>
  <last_deployment>2020-05-19 14:34:00 +0200</last_deployment>
  <commit>b8dac32ad172fdad843a31f455a9adff9a3efd71</commit>
</about>
```

**Comment by coolo** [comment]
Hmm, that would apply `_upload` was called with neither file_path nor data.

But why would you use `ac6e396`?

**Comment by aplanas** [comment]
I cannot clearly reproduce the issue. Can you use the current HEAD?

**Comment by aplanas** [comment]
you have write access to test:prj? The only option that I can think of is that the "put" fails. There is code that check if you have access rights to the target project, but I am not sure that work if the project do not exist (as the import will create it as a side effect)

Try the import in your home in OBS.

**Comment by jloeser** [comment]
Still occurs with e85c946.

I do have write access to test:prj.

Only the provided project by @coolo via unofficial channel gets imported without any issues.

**Comment by jloeser** [comment]
Same for home:
```
$ git show-ref --abbrev HEAD
e85c946 refs/remotes/upstream/HEAD
$ ./obsgit --level DEBUG --config ~/.obsgit-ebs2ebs import ./prj-export-5 home:jalo271589  
DEBUG:asyncio:Using selector: EpollSelector
Git LFS extension enabled in the repository
DEBUG:__main__:Start upload to source/home:jalo271589/_attribute
DEBUG:__main__:Start upload to source/home:jalo271589/_meta
DEBUG:__main__:Start upload to source/home:jalo271589/_pattern
Traceback (most recent call last):
  File "./obsgit", line 1336, in <module>
    loop.run_until_complete(args.func(args, config))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "./obsgit", line 1219, in import_
    await importer.project(project)
  File "./obsgit", line 836, in project
    await self.project_metadata(project)
  File "./obsgit", line 883, in project_metadata
    for meta in metadata
  File "./obsgit", line 129, in upload
    await self._upload(url_path, filename_path=filename_path, data=data, **params)
  File "./obsgit", line 123, in _upload
    if resp.status != 200:
UnboundLocalError: local variable 'resp' referenced before assignment
```

**Comment by aplanas** [comment]
Ahm ... So @coolo is right, the only other option is that filename_path and data are empty or None. This can be when a metadata file is empty and there is nothing to replace.

I added a new commit (https://github.com/aplanas/obsgit/commit/0d2a585650ccc470f24168c23866e6081e5c1f94). Can you test the new HEAD?

**Comment by jloeser** [comment]
Looks better now with recent changes. Thanks, can be closed.
